### ISSUE TITLE
UI/UX Improvements: order-now.html

### ISSUE THREAD

**Issue by yyingxuann** [SETP24Team6/SETP#17]
**Page: order-now.html**

- login form should come before location
- heading from customer-home (as per image below) should be present in order-now page

![Image](https://github.com/user-attachments/assets/f775432b-efcf-4563-8875-f25482701c5b)

**location form**
- "pickup" seems disguised as an unclickable button (as a user, i keep trying to click it) - maybe adjust this to a prompt that says only pickup is available (?) or make a greyed out "delivery" as aesthetic
- cannot see the text to "select a store"
- background is harsh in color, either lower opacity or add a white border around the entire form

![Image](https://github.com/user-attachments/assets/0d8ce039-6532-4934-b81c-9aae3bbfeacf)

**login form**
- "submit" button should be below the password, same for "reset password" button
![Image](https://github.com/user-attachments/assets/a5a336c0-153b-4b56-aea1-ac9a57aada30)
- possible to make the "forget password" smaller similar to below?
![Image](https://github.com/user-attachments/assets/16d2922a-d659-45cf-ae42-89f2c56c54c5)
- since db is not up yet, no pw validation - ensure there is a prompt for wrong password later on
**[functionality]** - reset password: should be done via email and sent to a new page, not as a "new password" field (?) - security risk
![Image](https://github.com/user-attachments/assets/bbcfb936-3085-4643-868a-68572aa9a78e)
**[functionality]** - there's a prompt for > 8 characters for when forgetting and changing new pw, but no initial prompt in the registration form
![Image](https://github.com/user-attachments/assets/d3369bcd-d152-4d4a-9c7b-d028cd6b9186)
**[functionality]** - after clicking "reset pw" button, brings you back to location page - clicking "start order" takes you to pre-filled (should not be pre-filled in any circumstances) "reset password" page instead of login page

**Comment by jumanahaseenn** [comment]
fixed the following items per comments above:
![image](https://github.com/user-attachments/assets/9f502859-4c45-4f19-b193-759b21b290f0)
![image](https://github.com/user-attachments/assets/43a5c8f4-1bfc-4322-a6a9-9645df35e067)
![image](https://github.com/user-attachments/assets/363847b3-82ed-497a-b59b-8070f752911e)
![image](https://github.com/user-attachments/assets/9ae12d8f-fc36-4f57-97e9-8e159100c881)
![image](https://github.com/user-attachments/assets/e785a39a-84a5-4276-b754-7d6bf569fea2)
